// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoepbvaufpokdagkfviw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZXBidmF1ZnBva2RhZ2tmdml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDE0ODUsImV4cCI6MjA2Njk3NzQ4NX0.xAYebjG7vl0_GLJpwNqeZMxl_TxTJnXOGD7RhS164cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});